=== Ervacon/webflow/src/com/ervacon/springframework/web/servlet/mvc/webflow/web-flow.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
	(c) Copyright Ervacon 2004-2005.
	All Rights Reserved.
-->

<!--
	Web flow DTD
	Authors: Erwin Vervaet
	
	This DTD defines the web flow XML syntax. Web flows capture the page flow
	in (part of) a web application.

	XML documents that conform to this DTD should declare the following doctype:

	<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN"
		"http://www.ervacon.com/dtd/web-flow.dtd">
-->


<!--
	Defines the root element for a web flow definition. Web flows
	are composed of a number of states.
-->
<!ELEMENT web-flow (
	start-state,
	(action-state | view-state | flow-state | end-state)+
)>

<!--
	Name of the web flow.
-->
<!ATTLIST web-flow name CDATA #REQUIRED>

<!--
	Defines the start state of the flow. This identifies the state
	where flow execution will begin.
-->
<!ELEMENT start-state EMPTY>

<!--
	Name of the first state of the flow.
-->
<!ATTLIST start-state state IDREF #REQUIRED>


<!--
	Defines an action state: a state where an action is executed.
	Transitions triggered by the action(s) lead on to other states.
-->
<!ELEMENT action-state (
	action+, transition+
)>

<!--
	Unique id of an action state.
-->
<!ATTLIST action-state id ID #REQUIRED>


<!--
	Defines a view state: a state where a view will be rendered.
	Transitions triggered by the view lead on to other states.
-->
<!ELEMENT view-state (
	transition*
)>

<!--
	Unique id of a view state.
-->
<!ATTLIST view-state id ID #REQUIRED>

<!--
	Name of the view that will be rendered. This is optional. When
	not present, the response should have been generated elsewhere,
	e.g. in an action of an action state.
-->
<!ATTLIST view-state view CDATA #IMPLIED>


<!--
	Defines a flow state: a state where another flow is executed. When the
	sub flow reaches an end state, the corresponding transition in this state
	is triggered to continue the flow.
-->
<!ELEMENT flow-state (
	transition*
)>

<!--
	Unique id of a flow state.
-->
<!ATTLIST flow-state id ID #REQUIRED>

<!--
	Name of the flow that will be rendered. This is the name of a bean
	in the application context associated with the flow controller.
-->
<!ATTLIST flow-state flow CDATA #REQUIRED>

<!--
	Optional name of a mapper that will map model data to and from the sub flow.
	This is the name of a bean in the application context associated with the
	flow controller.
-->
<!ATTLIST flow-state model-mapper CDATA #IMPLIED>


<!--
	Defines an end state: a state that terminates the flow.
-->
<!ELEMENT end-state EMPTY>

<!--
	Unique id of an end state.
-->
<!ATTLIST end-state id ID #REQUIRED>

<!--
	Name of the view that will be rendered. This is optional.
-->
<!ATTLIST end-state view CDATA #IMPLIED>


<!--
	Defines a transition to another state.
-->
<!ELEMENT transition EMPTY>

<!--
	Name of the transition. This name is of the form "[actionId'.']event". So
	the name of the event that will trigger the transition is prepended with
	the id of the action that signals the event. Both are cancatenated using
	a dot. So when you have an action with id "myAction" that signals an
	event "ok", the name of the corresponding transition should be "myAction.ok".
	
	For the events signaled by a view state or a subflow state, no action is involved so
	the transition name is simply the name of the event that triggers the transition
	("ok" in the previous example).
-->
<!ATTLIST transition name CDATA #REQUIRED>

<!--
	Target state of the transition.
-->
<!ATTLIST transition to IDREF #REQUIRED>


<!--
	Defines an action that is executed by the flow in an action state.
-->
<!ELEMENT action EMPTY>

<!--
	Name of the action.
-->
<!ATTLIST action name CDATA #REQUIRED>

<!--
	Name of the bean definition of the action in the application context
	hierarchy linked with the flow. This is similar to the <ref bean="myBean"/>
	notation of the Spring beans DTD.
-->
<!ATTLIST action bean CDATA #REQUIRED>

=== Ervacon/webflow/test/com/ervacon/springframework/web/servlet/mvc/webflow/searchStock-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN" "http://www.ervacon.com/dtd/web-flow.dtd">

<web-flow name="Search Stock Flow">
	
	<start-state state="criteria"/>

	<view-state id="criteria" view="criteria">
		<transition name="search" to="validateCriteria"/>
		<transition name="stop" to="endOk"/>
	</view-state>
	
	<action-state id="validateCriteria">
		<action name="bindAct" bean="bindCriteriaAction"/>
		<action name="validateAct" bean="validateCriteriaAction"/>
		<transition name="bindAct.error" to="criteria"/>
		<transition name="validateAct.ok" to="doSearch"/>
		<transition name="validateAct.error" to="criteria"/>
	</action-state>
	
	<action-state id="doSearch">
		<action name="doSearchAct" bean="searchAction"/>
		<transition name="doSearchAct.ok" to="results"/>
		<transition name="doSearchAct.error" to="endError"/>
	</action-state>

	<view-state id="results" view="results">
		<transition name="newSearch" to="criteria"/>
		<transition name="detail" to="bindSelection"/>
		<transition name="stop" to="endOk"/>
	</view-state>
	
	<action-state id="bindSelection">
		<action name="bindAct" bean="bindSelectionAction"/>
		<transition name="bindAct.ok" to="stockDetail"/>
		<transition name="bindAct.error" to="endError"/>
	</action-state>
	
	<flow-state id="stockDetail" flow="stockDetailFlow" model-mapper="stockDetailModelMapper">
		<transition name="endOk" to="results"/>
		<transition name="endError" to="endError"/>
	</flow-state>
	
	<end-state id="endOk"/>
	<end-state id="endError" view="error"/>
	
</web-flow>

=== Ervacon/webflow/samples/ItemList/WEB-INF/itemList-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN" "http://www.ervacon.com/dtd/web-flow.dtd">

<web-flow name="Item List Flow">

	<start-state state="list"/>

	<view-state id="list" view="list">
		<transition name="new" to="newItem"/>
	</view-state>

	<action-state id="newItem">
		<action name="newItemAct" bean="newItemAction"/>
		<transition name="newItemAct.ok" to="item"/>
	</action-state>
	
	<view-state id="item" view="item">
		<transition name="add" to="addItem"/>
	</view-state>
	
	<action-state id="addItem">
		<action name="addItemAct" bean="addItemAction"/>
		<transition name="addItemAct.ok" to="list"/>
		<transition name="addItemAct.tokenError" to="list"/>
	</action-state>
	
	<end-state id="endError" view="error"/>
	
</web-flow>

=== Ervacon/webflow/test/com/ervacon/springframework/web/servlet/mvc/webflow/stockDetail-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN" "http://www.ervacon.com/dtd/web-flow.dtd">

<web-flow name="Stock Detail Flow">
	
	<start-state state="doGetDetail"/>

	<action-state id="doGetDetail">
		<action name="getDetailAct" bean="getDetailAction"/>
		<transition name="getDetailAct.ok" to="detail"/>
		<transition name="getDetailAct.error" to="endError"/>
	</action-state>
	
	<view-state id="detail" view="detail">
		<transition name="back" to="endOk"/>
	</view-state>
	
	<end-state id="endOk"/>
	<end-state id="endError" view="error"/>
	
</web-flow>

=== Ervacon/webflow/samples/PhoneBook/WEB-INF/search-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN" "http://www.ervacon.com/dtd/web-flow.dtd">

<web-flow name="Search Flow">

	<start-state state="criteria"/>

	<view-state id="criteria" view="criteria">
		<transition name="search" to="bindAndValidateCriteria"/>
	</view-state>

	<action-state id="bindAndValidateCriteria">
		<action name="bindAndValidateAct" bean="bindAndValidateCriteriaAction"/>
		<transition name="bindAndValidateAct.ok" to="search"/>
		<transition name="bindAndValidateAct.error" to="criteria"/>
	</action-state>
	
	<action-state id="search">
		<action name="searchAct" bean="queryAction"/>
		<transition name="searchAct.ok" to="results"/>
	</action-state>
	
	<view-state id="results" view="results">
		<transition name="newSearch" to="criteria"/>
		<transition name="detail" to="bindAndValidateId"/>
	</view-state>

	<action-state id="bindAndValidateId">
		<action name="bindAndValidateAct" bean="bindAndValidateIdAction"/>
		<transition name="bindAndValidateAct.ok" to="detail"/>
		<transition name="bindAndValidateAct.error" to="endError"/>
	</action-state>
	
	<flow-state id="detail" flow="detailFlow" model-mapper="idMapper">
		<transition name="endOk" to="results"/>
		<transition name="endError" to="endError"/>
	</flow-state>
	
	<end-state id="endError" view="error"/>
	
</web-flow>

=== Ervacon/webflow/samples/FileUpload/WEB-INF/upload-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN" "http://www.ervacon.com/dtd/web-flow.dtd">

<web-flow name="File Upload Flow">

	<start-state state="select"/>

	<view-state id="select" view="select">
		<transition name="upload" to="processUpload"/>
	</view-state>

	<action-state id="processUpload">
		<action name="processUploadAct" bean="processUploadAction"/>
		<transition name="processUploadAct.ok" to="confirmation"/>
		<transition name="processUploadAct.error" to="select"/>
	</action-state>
	
	<view-state id="confirmation" view="confirmation">
		<transition name="back" to="select"/>
	</view-state>
	
</web-flow>

=== Ervacon/webflow/samples/PhoneBook/WEB-INF/detail-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN" "http://www.ervacon.com/dtd/web-flow.dtd">

<web-flow name="Detail Flow">

	<start-state state="getDetail"/>
	
	<action-state id="getDetail">
		<action name="getDetailAct" bean="getPersonAction"/>
		<transition name="getDetailAct.ok" to="detail"/>
		<transition name="getDetailAct.error" to="endError"/>
	</action-state>

	<view-state id="detail" view="detail">
		<transition name="back" to="endOk"/>
		<transition name="colleagueDetail" to="bindAndValidateColleagueId"/>
	</view-state>

	<action-state id="bindAndValidateColleagueId">
		<action name="bindAndValidateAct" bean="bindAndValidateColleagueIdAction"/>
		<transition name="bindAndValidateAct.ok" to="colleagueDetail"/>
		<transition name="bindAndValidateAct.error" to="endError"/>
	</action-state>
	
	<flow-state id="colleagueDetail" flow="detailFlow" model-mapper="colleagueIdMapper">
		<transition name="endOk" to="detail"/>
		<transition name="endError" to="endError"/>
	</flow-state>
	
	<end-state id="endOk"/>
	<end-state id="endError" view="error"/>
	
</web-flow>

=== Ervacon/webflow/samples/BirthDate/WEB-INF/birthDate-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE web-flow PUBLIC "-//ERVACON//DTD SPRING WEB FLOW//EN" "http://www.ervacon.com/dtd/web-flow.dtd">

<!-- 
	This simple flow demonstrates the use of the SimpleFormAction: a multi-action
	that allows you to mimic the exact behaviour of the SimpleFormController in a flow.
	Notice how all the actions use the same "birthDateFormAction" bean, which groups
	all actions executed by this flow in single class!
	
	Note that this flow implements the exact flow of the SimpleFormController as an example.
	If you only need this flow, it is advised that you just use the SimpleFormController.
-->
<web-flow name="Birth Date Flow">

	<start-state state="prepareNewForm"/>
	
	<!--
		Prepare to display a new form. This is very similar to the showNewForm() method
		of the SimpleFormController: it basically initializes the binder so that all property
		editors are available for form display.
	-->
	<action-state id="prepareNewForm">
		<action name="prepare" bean="birthDateFormAction"/>
		<transition name="prepare.ok" to="formView"/>
	</action-state>
	
	<!--
		Display the input form view.
	-->
	<view-state id="formView" view="enterBirthDate">
		<transition name="submit" to="bindAndValidate"/>
	</view-state>
	
	<!--
		Bind and validate input data from the form. This is similar to the bindAndValidate()
		method of the SimpleFormController.
	-->
	<action-state id="bindAndValidate">
		<action name="bindAndValidate" bean="birthDateFormAction"/>
		<transition name="bindAndValidate.ok" to="calculateAge"/>
		<transition name="bindAndValidate.error" to="formView"/>
	</action-state>
	
	<!--
		Process a successful submit. This is similar to the onSubmit() method of the
		SimpleFormController.
	-->
	<action-state id="calculateAge">
		<action name="calculateAge" bean="birthDateFormAction"/>
		<transition name="calculateAge.ok" to="successView"/>
	</action-state>
	
	<!--
		Display the success view.
	-->
	<end-state id="successView" view="displayAge"/>

</web-flow>
